
tasks:
  - init: |
      echo 'init script' # runs during prebuild
      touch file.init
    command: |
      echo 'start script'
      touch file.cmd
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - golang.go