
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: false
    addLabel: prebuild-in-gitpod
tasks:
  - name: init
    init: |
      go install
      go get -u github.com/cosmtrek/air
    command: |
      docker-compose up -d
      air
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore  

vscode:
  extensions:
    - golang.go