image:
  file: .gitpod.Dockerfile
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: false
    addLabel: prebuild-in-gitpod
tasks:
  - name: init
    init: |
      go install
      go get -u github.com/cosmtrek/air
      mysql -e "create database golang"
      mysql golang < database/docker_images.sql
    command: |
      cd src
      air
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview 

vscode:
  extensions:
    - golang.g