version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: golang
      MYSQL_PASSWORD: golang
      MYSQL_ROOT_PASSWORD: golang
      MYSQL_DATABASE: golang
    # sync folders. MySQL data is stored outside container so that rebuilding doesn't clear db.
    # folder is at workspace root.
    volumes:
      - ./database/local_mysql_data:/var/lib/mysql
      - ./database/docker_images.sql:/docker-entrypoint-initdb.d/docker_images.sql  
