version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerimages/web/Dockerfile
    # ports from container exposed to the docker machine and the guest machine
    ports:
      # 80 on the host, 8080 on the guest. Websever listens on 8080
      - "80:8080" # http
    # file with environment declarations for the container
    env_file:
      - dockerimages/web/.env
    # Link to containers in another service
    links:
      - db
    # sync workspace folder with /go
    volumes:
     - ./src:/go
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: golang
      MYSQL_PASSWORD: golang
      MYSQL_ROOT_PASSWORD: golang
      MYSQL_DATABASE: golang
    # sync folders. MySQL data is stored outside container so that rebuilding doesn't clear db.
    # folder is at workspace root.
    volumes:
      - ./database/local_mysql_data:/var/lib/mysql